apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-web
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: training-web
  template:
    metadata:
      labels:
        app: training-web
    spec:
      containers:
      - image: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/appstellar/training-web:latest
        name: training-web
        ports:
        - containerPort: 3000
