apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
images:
- name: training-web
  newName: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/appstellar/training-web
  newTag: e5dab94b24e120e58b1fb291e255d8edd796226d
