name: deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 313422618945.dkr.ecr.eu-central-1.amazonaws.com
          docker build -f ./Dockerfile -t appstellar/training-web .
          docker tag appstellar/training-web:latest ${{ secrets.AWS_ECR_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ECR_URI }}:${{ env.IMAGE_TAG }}
          
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.8.4"
          
      - name: Update Kubernetes resources
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.AWS_ECR_URI }}:${{ github.sha }}
        run: |
         cd k8s
         kustomize edit set image apptellar/training-web=$DOCKER_IMAGE_NAME
         
      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Update Kubernetes"
